### ISSUE TITLE
[BUG] JSON keys with dot conflicts

### ISSUE THREAD

**Issue by PHClement** [tolgee/tolgee-platform#1033]
Hello,

First of all great open source project !

ISSUE : When you use dot to separate your keys the json files will create conflicts between keys
EXAMPLE :  `auth.login.forgot_password` and `auth.login.help_text`

SUGGESTED SOLUTION : Parse dot (.) as nested object in JSON 

SEE : [Example in file](https://app.meilleursbiens.com/i18n/fr.json)

**Comment by JanCizmar** [comment]
Hi there! Can you describe how to reproduce this? There are multiple ways, how to export. Also, which version are you using?

**Comment by JanCizmar** [comment]
> EXAMPLE : auth.login.forgot_password and auth.login.help_text

This example wouldn't conflict. What is a problem is that your project contains these keys 
- "auth.login" - (with value "Connexion" in your example)
- "auth.login.two_factor_auth.description" - (with value "Rendez-vous dans l'applica...")

This is impossible to handle by the export method, since the auth.login is already occupied by string value, so it cannot create a nested object.

So it would look like this, when it was scoped which is invalid json:
```
{
  "auth": {
    "login": "Connexion"
    "login": {
      "two_factor_auth": {
        "description": "Rendez-vous dans l'applica..."
      }
    }
  }
}
```

```
{
  "auth": {
    "login": "Connexion"
    "login": {
     ^^
     Conflicting key.
-------------------------
      "two_factor_auth": {
        "description": "Rendez-vous dans l'applica..."
      }
    }
  }
}
```

So it's not a bug it is a feature. When conflict like this appears, it is added to root by the export method.

However, there is a V2 export isn't accessible with api key yet. But I'll fix it and let you know.
