### ISSUE TITLE
Figma plugin

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#1385]
- [x] Create plugin to Figma enabling users to create keys and modify translation similarly as in the web dev-tools

The Figma plugin has been [released](https://tolgee.io/blog/figma-plugin)!
For more information, you can visit the [documentation](https://tolgee.io/platform/figma-plugin/setup) and the [GitHub repository](https://github.com/tolgee/figma-plugin).

**Comment by eweren** [comment]
Here is a small POC: https://github.com/eweren/figma-plugin-tolgee

My idea was: The name of the TextNode has to be the related tolgee key - prefixed by `t:`.
The plugin gets notified, that there is a new key and adds it to your tolgee project.
If you edit the content afterwards, the name of the TextNode won't be autoRenamed so that it will keep it's tolgee-related name. After editing and unfocusing the node, the related tolgee entry will be renamed.

The structure should be self explained by looking at those two screenshots:

<img width="603" alt="Bildschirm­foto 2022-11-13 um 19 10 27" src="https://user-images.githubusercontent.com/25116822/201537406-07c636b7-1888-4d5b-b07d-ee2079908a87.png">
<img width="214" alt="Bildschirm­foto 2022-11-13 um 19 14 01" src="https://user-images.githubusercontent.com/25116822/201537502-c59ba985-0597-4271-a3d8-c1ef55ed90df.png">

You will be prompted to enter your credentials (url+apiKey+initial language) on first startup -> without validation so you should enter the correct credentials right now.

I don't have any experience in developing a figma plugin so I do not know if the plugin will run continuously in the background.

It seems like you do not have access to user events like clicks or hovers, so I came up with this idea of using the Nodes name.

There is no polished ui, or error handling or whatever, but I guess this is poc enough ;)

**Comment by Martin005** [comment]
The Figma plugin has been [released](https://tolgee.io/blog/figma-plugin)!
For more information, you can visit the [documentation](https://tolgee.io/platform/figma-plugin/setup) and the [GitHub repository](https://github.com/tolgee/figma-plugin).
