### ISSUE TITLE
Feature request: tree view for translations

### ISSUE THREAD

**Issue by ecstrema** [tolgee/tolgee-platform#1615]
In this view:
![image](https://user-images.githubusercontent.com/35939574/223733539-358505cd-1c4f-4f25-add8-99725b27c99d.png)

Could it be possible to add an option to view the keys in a tree view?

**Comment by JanCizmar** [comment]
Hi there!

Thanks for the idea! 🚀

The thing is... We don't treat the `.` character as nesting delimiter by default anymore.

Anyway, implementation of treeview would be extremely complicated, since it affects pagination, filtering, etc. Use namespaces if you want to structure the data, that's the recommend way.

**Comment by ecstrema** [comment]
Thanks for the quick reply.

Do you mind if I give it a go? Although it might need some thoughts for pagination and filtering, this page is way harder to use with filtering, and namespacing every single tiny unit is impossible, or at least impracticable.

> The thing is... We don't treat the `.` character as nesting delimiter by default anymore.

But, when the data is exported, it is still treated as such, isn't it? Also, it should be quite easy to detect with the ratio of . over the number of letters in the keys.

> implementation of treeview would be extremely complicated, since it affects pagination, filtering, etc.

For now, I'd like to load all the data directly on memory, and disable the tree view for large projects (more than a few thousand keys). Filtering is a known (and solved) problem for tree views, and I'd love to reuse my algorithm classes for that:)

**Comment by stepan662** [comment]
Hey, it depends on what do you mean by "tree view". We've dropped the idea to treat translations as tree on backend because it adds a lot of complexity. 

It could be possible to "simulate" the tree view by filtering only keys with certain prefix and then hiding this prefix from the user. This could be probably done quite easily.

**Comment by ecstrema** [comment]
Yeah, nothing on the backend. For the example above:

![image](https://user-images.githubusercontent.com/35939574/224463214-34a6087b-4ffb-4586-a21a-045c4ea74eed.png)

Would make up for something like this [stackblitz project](https://stackblitz.com/edit/react-lkmtmh?file=app%2Fmain.jsx).
