### ISSUE TITLE
Support custom MT webservice

### ISSUE THREAD

**Issue by roeycohen** [tolgee/tolgee-platform#1655]
Hi,
Are there any plans to embed translations via chat gpt?
One of the benefits of chat gpt is that we can tell him how to translate specific words or phrases, so they will be translated later in the same manner...

**Comment by Martin005** [comment]
Hello @roeycohen!
We are planning on releasing our own [AI Translator #1543](https://github.com/tolgee/tolgee-platform/issues/1543) in the very near future 🙂
Also, when developing the [Glossary feature #1418](https://github.com/tolgee/tolgee-platform/issues/1418), we will enhance this AI Translator so it will provide you with translations that are consistent with your glossary.

**Comment by roeycohen** [comment]
amazing @Martin005, 

I think it could be a nice to also add a custom webservice integration where Tolgee can send a text and desired language get back the translation from the client's server... 
On our case we have a small service that talk to CHAT-GPT and it could be great if we could just make it work with Tolgee...

**Comment by Martin005** [comment]
@roeycohen
Thanks for the feedback! 🙂
Yes, I agree that a custom webservice integration would be great. Unfortunately, it doesn't fit into our current development plan. 

But if you are courageous enough, you can try to implement this feature.
I think it wouldn't be that hard to do it; you can check out the [PR for Baidu machine translation support](https://github.com/tolgee/tolgee-platform/pull/1606) that was done by the community member @wfjsw. Basically, it gets the text string for translations, sends an HTTP request to Baidu's server and returns back the translation.

**Comment by roeycohen** [comment]
ok @Martin005, I'm not familiar with Kotlin, but I'll might give it a go.

Thanks for this project again :)

**Comment by JanCizmar** [comment]
@roeycohen You'll love it.

**Comment by horstmannmat** [comment]
Hi, I think that would be cool to have an "abstract" API to use machine learning translation instead of one per service, so anyone can develop the wrapper without needing to change the code.

The abstract would receive an API URL (wrapper), API secret (optional), text, from, and to as parameters.

The wrapper would be responsible for translating the incoming request to the specific Translator. It can be a micro-service,

And the good thing about this approach is that you don't need to change the code every time a new AI or translator appears. 
Anyone can it own service, for example, I do not think that Deepl/google have a good translation for Euskara, I use [Elia](https://elia.eus/translator). I could create a wrapper for that

**Comment by JanCizmar** [comment]
Hello, indeed it would be cool. But we are not really motivated to provide such API since providing this ability would kind of go agains against our monetization model. However, if you submit a PR for this we will probably approve it, since I don't really belive many user would be interested into implementing their own translation service.

**Comment by horstmannmat** [comment]
Even if only "business" or "enterprise" was allowed in a non-self-hosted environment? 

I will try to understand kotlin, but I think that it will require a new screen to add the infos, such as "allowed languages" "name" etc

Also it would require a new database table to save those info

**Comment by JanCizmar** [comment]
Hello, since there are not many from the community are requesting this, I am closing it for now.
