### ISSUE TITLE
DeepL Machine Translation not working for Turkish | Türkçe (tr)

### ISSUE THREAD

**Issue by cdemi** [tolgee/tolgee-platform#1695]
Hi,

We have a self-hosted installation and we're using DeepL Machine Translation. For all our other languages, DeepL Machine Translation returns translations, however for some reason for `Turkish | Türkçe (tr)` we don't get any translations. I have checked the DeepL API and they do support Turkish `TR`. I have also called the DeepL API manually and it does give me a valid translation.

![image](https://user-images.githubusercontent.com/8025435/235907059-0b049f20-2d03-4183-a87d-5860a1241052.png)

On inspecting the POST to `/v2/projects/1/suggest/machine-translations`, this is the response I get from the backend:

```json
{
    "machineTranslations": {
        "DEEPL": null
    },
    "translationCreditsBalanceBefore": -1,
    "translationCreditsBalanceAfter": -1,
    "translationExtraCreditsBalanceBefore": 0,
    "translationExtraCreditsBalanceAfter": 0
}
```

I don't see any error logs on the server

Would you be able to show me what I am doing wrong 🙏

**Comment by Martin005** [comment]
Hello @cdemi 🙂 
Thanks for the report!

We keep list of supported languages for each Machine Translation provider in code. You can find the list of currently supported languages through DeepL in Tolgee [here](https://github.com/tolgee/tolgee-platform/blob/main/backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/DeeplTranslationProvider.kt#L26-L54).
Since the implementation of DeepL into Tolgee, DeepL has added support for [Turkish and Indonesian](https://www.deepl.com/en/blog/deepl-welcomes-turkish-and-indonesian), [Ukrainian](https://www.deepl.com/en/blog/deepl-learns-ukrainian) and [Korean and Norwegian (bokmål)](https://www.deepl.com/en/blog/welcome-korean-and-norwegian). But we haven't added these languages to our list. I will update the list shortly 🙂

**Comment by cdemi** [comment]
Thanks @Martin005. I figured it out after I opened the issue and I have opened a PR, hopefully it's correct lol

**Comment by Martin005** [comment]
@cdemi Ah, you were quicker than I anticipated 😄
Yes, that is correct way to add more languages. **Please also add "id" to the list** for Indonesian 🙂

**Comment by cdemi** [comment]
Done, thanks a lot!

**Comment by cdemi** [comment]
Thanks for the quick action. By any chance (I know it's unrelated), do you know if there's a way to machine translate all keys when a new language is added?

**Comment by Martin005** [comment]
@cdemi
Unfortunately, there is no way to translate through MT all keys when a new language is added at the moment. But we plan to add this feature as a batch operation (after selecting all keys) in [Batch Operations #911](https://github.com/tolgee/tolgee-platform/issues/911).
