### ISSUE TITLE
Android export/import issues

### ISSUE THREAD

**Issue by Nailik** [tolgee/tolgee-platform#2212]
Hi while testing i found some more issues with Android import export:

- importing ` \n\n` exports to `"\n\n"`
- `<![CDATA[` is not always recognized (in my example it starts with `<![CDATA[<b>` maybe that's the issue
- `\u2022` is not recognized and will be escaped to `\\u2022`
- importing `%1$s %2$s` etc exports to `%s %s` -> seems like a bug because the ui shows 2 different placeholders (with id 0 and 1)

**Comment by JanCizmar** [comment]
Hey! The Android import and export is currently so complex, I cannot simply guess, what's the actual and desired behaviour for each of the cases you've reported. Can you please share the exact relevant parts of Android Strings XML, you are importing and the relevant parts being exported?

> importing %1$s %2$s etc exports to %s %s -> seems like a bug because the ui shows 2 different placeholders (with id 0 and 1)

This is intended, since it has exactly the same meaning. You can omit the `1$` and `2$`, when you don't need to modify the order of the placeholders being rendered in the text.

**Comment by Nailik** [comment]
- any `\n\n` should be exported as `\n\n` because it's just to newlines
example: 
`<string name="some_text">text\n\nmore text</string>`
is exported as  `<string name="some_text">text"\n\n"more text</string>`
- Unicode characters like `\u2022` should not be escaped
example: 
`<string name="some_bullet_text">\u2022 some text</string>`
is exported as  `<string name="some_bullet_text">\\u2022 some text</string>`


For 
`<![CDATA[ `is not always recognized (in my example it starts with `<![CDATA[<b>` maybe that's the issue
actually `CDATA` was recognized because the text contains the `_androidWrapWithCdata` flag but html tags are encoded.
The string uses the following html tags:
- b
- br
- a
- span
- ul
- li
The string should be wrapped with CDATA instead of being html encoded

**Comment by JanCizmar** [comment]
> `<string name="some_text">text\n\nmore text</string>`

Thanks, you're right here that \n is always rendered as new line despite it's quoted or not...

> <![CDATA[ is not always recognized (in my example it starts with <![CDATA[<b> maybe that's the issue
actually CDATA was recognized because the text contains the _androidWrapWithCdata flag but html tags are encoded.

Can you also share an example of such string which is not being recognized?

**Comment by JanCizmar** [comment]
> Could you add an export option to disable this? i really would like it because it shows more specific that there are multiple parameters when using 1$ and 2$ ...

The thing is that we don't really want to complicate the UI and overall importing / exporting process. You shouldn't care much about the syntax of the data exported from Tolgee, since you are probably don't have to modify them. `.. %s .. %s` is perfectly valid syntax for your case. I don't see much need for having such export option, which is useless from semantic point of view, right?

**Comment by JanCizmar** [comment]
You're right, this is a bug in export behaviour. Thanks for the valuable feedback!

**Comment by JanCizmar** [comment]
> <string name="sometext"><![CDATA[<a href=\"%1$s://link\">Link</a> und <a href=\"%1$s://link2\">Link2</a>]]></string>

I have tested this case and it works correctly. 

It imports the placeholders as `{0} ... {0}` and exports as: <string name="sometext"><![CDATA[<a href=\"%s://link\">Link</a> und <a href=\"%1$s://link2\">Link2</a>]]></string>

Which perfectly works.

**Comment by Nailik** [comment]
my bad, wrong import i imported with `<string name="sometext"><![CDATA[<a href=\"%s://link\">Link</a> und <a href=\"%s://link2\">Link2</a>]]>`
