### ISSUE TITLE
Cannot disable user when over free limit on self-hosted instance

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2219]
It throws an "over limit" error when trying to disable user. This can happen when instance with > 10 users is upgraded from pre-limit version to latest.

**Comment by bastijns-jeroen** [comment]
Hi @JanCizmar, we are running a self-hosted instance for about a year now, fixed on version 3.61.0. We have the same issue as this one. We are still getting the limit exceeded error. We can delete users, that is not an issue. We currently have only 6 users.
Do you know what could fix the issue? I've been reading through the later release versions but couldn't find a commit where this issue is further addressed.

**Comment by bastijns-jeroen** [comment]
Nevermind, found other users under server administration which accounted for 10 users.
A bit difficult to find :-D

**Comment by JanCizmar** [comment]
Hello! Sorry for late reply and thanks for reporting. Yes. Indeed, this information can be found in the server administration.
