### ISSUE TITLE
REST API: Translations - Return translations in project endpoint

### ISSUE THREAD

**Issue by xmajzel** [tolgee/tolgee-platform#2229]
Endpoint does not work correctly in following cases:

**Link to endpoint in API Docs:** https://tolgee.io/api#tag/Translations/operation/getTranslations_1

## Case 1

**Current behaviour:**
- When using `filterUntranslatedAny` searchParameter, no keys are returned.

**Expected behaviour:**
- Keys, where translation is missing in any language should be returned.

**Search params:**

```ts
{
  filterUntranslatedAny: true
}
```

## Case 2

**Current behaviour:**
- When using `filterUntranslatedInLang` searchParameter are returned also keys, which already have translation in specified language.

**Expected behaviour:**
- Only keys, where translation is missing in specified language should be returned.

**Search params:**

```ts
{
  filterUntranslatedInLang: 'fi'
}
```

**Workaround:**
- When specifying `languages` searchParameter, the endpoint magically starts working.

**Workaround search params:**

```ts
{
  filterUntranslatedInLang: 'fi',
  languages: ['en', 'fi']
}
```

**Comment by JanCizmar** [comment]
Hello! Thanks for reporting. What languages are returned when you provide no `languages` query param? 

Seems like Case 1 and Case 2 have the same cause. It only filters in languages which are returned - implicit languages or the languages provided in `languages` query param. 

This behaviour was intended, because the endpoint is designed for the UI of Tolgee it wouldn't make sense to filter in languages you don't retrieve. Truth is, this should be documented or it should filter also in other languages.

**Comment by xmajzel** [comment]
Without providing `languages` param, translations for `en` and `cs` languages are returned.
- `en` is default language
- `cs` is first language, if I open filter on following page `https://{tolgeeURL}/projects/{ID}/translations`

> Truth is, this should be documented or it should filter also in other languages.

Okay, I definitely agree with that. I don't have a preference between the proposed solutions, both are fine.
