### ISSUE TITLE
Machine translation for keys with plural options seems broken

### ISSUE THREAD

**Issue by siepkes** [tolgee/tolgee-platform#2337]
It's me again, breaker of software :wink:.

When importing `test.properties`:

```
# The number of products the user has.
4554510126023382194={PRODUCT_COUNT_1,plural,=0{Je hebt geen producten.}=1{Je hebt één product.}other{Je hebt # producten.}}
```

the entries (with plural) are correctly imported in to Tolgee for Dutch (thanks for the quick fix in #2334 btw!). So that's great! However when I select the key and trigger the "Machine Translate" option on it this is the result:

![Screenshot from 2024-06-03 13-38-38](https://github.com/tolgee/tolgee-platform/assets/1428678/37afe4a6-9712-4c25-9a59-1f78cabde91c)

Maybe I missing something here but I don't think this is correct? I would expect the other languages like English to have a "zero" option as well (i.e. "You have no products.").

**Comment by JanCizmar** [comment]
Hey! Tolgee is currently not prepared to handle the exact (`=0`, `=1`) cases so well. We recommend to use the standard `zero`, `one` ... keywords, since these will convert correctly to other languages. 

**The background**:
As you can see in the official CLDR documentation [here](https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html), in some languages, it doesn't behave as you would expect. 

For example the `zero` form is used also for !=0 cases (e.g. in Latvian), so if you use the exact `=0`... forms, it can break pretty simply.

**Comment by siepkes** [comment]
Good point about the "zero" form use case.

I got this "questionable practice" from the Google Closure Templates documentation on [using messages](https://github.com/google/closure-templates/blob/master/documentation/reference/messages.md) within Closures Templates. Closure Templates has it's own message syntax (with plural support, etc.) for use in the templates which is extracted by a tool and converted to ICU message format so it can be used by translation tooling (like Tolgee). Apparently internally Google converts it to some other internal message format which they use for translation. 

Since Google probably translates a lot of stuff in a lot of languages it makes you wonder why they would document using the "zero" form like that (i.e. "You have no products" instead of "You have 0 products"). Since Closure Templates is basically more "source drops" then "opensource with a community" the docs give some insights in how Google does things internally.
