### ISSUE TITLE
Features maybe someone else also need 

### ISSUE THREAD

**Issue by Frooger** [tolgee/tolgee-platform#938]
Hi Everyone,

I tried out tolgee the last few days. I pretty like the simplificant of the app. Its pretty cool.
I have some ideas maybe someone also need it:

Can we apply users to the specific languages ? so only user A can edit english ? 
Why Translate role has the ability to export the translations ? - can we make it possible to enable / disable it 
Why Translate role has the ability to integrate ?  - can we make it possible to enable / disable it 

Inventions Links with expiry date ? 

Would be cool if these features could be added :)
If you need help i could also offer to help :)

Many Thanks

**Comment by JanCizmar** [comment]
Hi there! 
> Can we apply users to the specific languages ? so only user A can edit english ?
The language limitation for translate permission is already planned in #919.

> Why Translate role has the ability to export the translations ? - can we make it possible to enable / disable it
We thread permissions like levels, so when you have VIEW permission, you are able to see all the translations, so you are also able to export them, since you have access to the data. Why would you like disable it?

> Why Translate role has the ability to integrate ? - can we make it possible to enable / disable it
For the same reason. You can integrate with view permission. Then in the Togee UI, you won't be able to change anything but it would work. Your limited, but it works.

> Inventions Links with expiry date ?
Good point. Created new Issue for this - #939. I think constant expiration would be enough. What do you think?

Thanks a lot!

**Comment by Frooger** [comment]
Thank You for the fast reply :)

Translate Role disable integrate and export:
- I think it s different to give users ability to completly download all translations or just edit it. Because the file can be 
 shared with others directly and the ui of tolgee is secured with authentication.

Expiry Date:
Constant is ok but individual is maybe better for future :)

**Comment by JanCizmar** [comment]
Hmm, I am afraid that restricting users from export would change the whole way how we work with permissions. So maybe one day, but it's definitely not going to be done tomorrow.

**Comment by JanCizmar** [comment]
It's possible to set specific language for translate permission now. We currently don't plan to implement the rest of the enhancements, so I am closing this.
