### ISSUE TITLE
Project/Organization creation on self hosted instance

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-platform#976]
It appears localization data actually has the translation text, except the key has an extra `_error` at the end (see [en.json#L202](https://github.com/tolgee/server/blob/main/webapp/src/i18n/en.json#L202).) It seems other keys have this extra `_error` at the end, so there might be other keys with the same issue.

![image](https://user-images.githubusercontent.com/9999055/158064153-29681088-1491-401c-b12e-e7c422833af8.png)

**Comment by JanCizmar** [comment]
It seems like this happened due to refactoring of ApiHttpService which handled 403s before.

**Comment by JanCizmar** [comment]
Also, it's a bug you are able to get to the project form when the server has probably disabled project creation. Isn't it?

**Comment by cyyynthia** [comment]
> Also, it's a bug you are able to get to the project form when the server has probably disabled project creation. Isn't it?

The button is available despite project creation being off, however it seems the API doesn't expose (yet?) the user's role, so I assumed it was to still let the administrator create projects in this configuration.

**Comment by JanCizmar** [comment]
@stepan662 `/api/public/configuration` has `userCanCreateOrganizations ` and `userCanCreateProjects` props

**Comment by JanCizmar** [comment]
> however it seems the API doesn't expose (yet?)

Hmm. Yeah. That also would be a problem.

**Comment by cyyynthia** [comment]
> Hmm. Yeah. That also would be a problem.

Exposing the user's role will be necessary for conditionally showing a link to the admin screen for #974, so doing it now to solve project/org creation issues doesn't sound too bad at all to me. A separate issue can be made for it I guess

**Comment by JanCizmar** [comment]
Disabling of the project creation button is currently not what we want to do, since we want organization OWNER to be able to create an project in organization. 

That's why I cannot just expose the user role and disable the button. 

However, we are currently rebuilding the whole organization/user logic in `billing` branch, so every project will be owned by an Organization and so every user will have an organization. So it doesn't make sense to fix the project creation dialog, since the user-can-create-projects property will be useless later. 

So I am going to solve all of this in billing branch, which will be hopefully merged next week.

Disclamer: Billing branch doesn't mean that you will have to pay for this features. We are just preparing there for huge changes related to enabling billing of the Cloud / on-premiss services.

**Comment by JanCizmar** [comment]
This is now fixed, since all projects are part of an organizaton an server admin can create organizations ecent when userCanCreateOrganizations=false
